create table tb_hotel (
  id bigint generated by default as identity primary key,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nome text,
  cnpj text unique not null,
  pais text,
  estado text,
  cidade text
);