create table 
    tb_reservas (
    id bigint generated by default as identity primary key,
    inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    numeroreserva text,
    apartamento text,
    datacheckin text,
    datacheckout text,
    status text,
    idhotel bigint references tb_hotel(id)
    );
